version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: chat-backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      HOST: ${HOST:-0.0.0.0}
      PORT: 3000
      DB_DIALECT: ${DB_DIALECT:-sqlite}
      DB_STORAGE: ${DB_STORAGE:-/app/data/database.sqlite}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET: ${JWT_SECRET:-change_me_for_tests}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8080,http://localhost:5173,http://localhost}
    volumes:
      - backend_sqlite_data:/app/data
      - ./backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL:-http://localhost:3000}
    container_name: chat-frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_sqlite_data:
    driver: local
