version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DB_DIALECT: sqlite
      DB_STORAGE: /app/data/database.sqlite
      LOG_LEVEL: info
      JWT_SECRET: change_me_for_tests
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:8080,http://localhost:5173,http://localhost
    volumes:
      - backend_sqlite_data:/app/data
      - ./backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000/api
        VITE_SOCKET_URL: http://localhost:3000
    container_name: chat-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_sqlite_data:
    driver: local
